/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package urmsgui;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userTypeLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        userField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rememberCheckBox = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        buttonForgetPassword = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Projects\\Java\\GUI\\URMSGUI\\rss\\bannerResized.png")); // NOI18N

        jButton2.setText("Faculty Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Student Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        titleLabel.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        titleLabel.setText("Student Login");

        userTypeLabel.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        userTypeLabel.setText("Student ID");

        jLabel4.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel4.setIcon(new ImageIcon(new ImageIcon("computer.png").getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT)));
        jLabel4.setText("Password");

        rememberCheckBox.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        rememberCheckBox.setText("Remember me?");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        buttonForgetPassword.setForeground(new java.awt.Color(0, 153, 153));
        buttonForgetPassword.setText("Forgot Password");
        buttonForgetPassword.setBorder(null);
        buttonForgetPassword.setBorderPainted(false);
        buttonForgetPassword.setContentAreaFilled(false);
        buttonForgetPassword.setIconTextGap(0);
        buttonForgetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForgetPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rememberCheckBox)
                                .addGap(77, 77, 77)
                                .addComponent(buttonForgetPassword))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(userField)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTypeLabel)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rememberCheckBox)
                    .addComponent(buttonForgetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLabel)
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 209, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonForgetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForgetPasswordActionPerformed
        // TODO add your handling code here:
        buttonForgetPassword.setForeground(Color.red);
        JOptionPane.showMessageDialog(this, "Password reseted to the default one. Please contact the IT-Office at PB-207 during the office hour if you don't remember the default one either!");
    }//GEN-LAST:event_buttonForgetPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (titleLabel.getText().equalsIgnoreCase("student login")) {
            titleLabel.setText("Faculty Login");
            userTypeLabel.setText("E-mail");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (titleLabel.getText().equalsIgnoreCase("faculty login")) {
            titleLabel.setText("Student Login");
            userTypeLabel.setText("Student ID");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean checkBoxFac;
    private boolean checkBoxSt;
    private Person person;
    private String userFac;
    private String passFac;
    private String userSt;
    private String passSt;
    private Faculty faculty;
    private Student student;
    private static boolean fac = false;
    private StudentFrame studentFrame;
    private FacultyFrame facultyFrame;
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String password = userField.getText();
        String user = passwordField.getPassword().toString();
        auth(user, password);

    }//GEN-LAST:event_loginButtonActionPerformed

    private void clearFields() {
        userField.setText("");
        passwordField.setText("");
    }

    private void auth(String user, String password) {
        if (password != null && user != null) {
            if (userTypeLabel.getText().equalsIgnoreCase("student id")) {
                for (var x : students) {
                    if (x.getId().equals(user) && x.getPassword().equals(password)) {
                        student = x;
                        fac = false;
                        if (rememberCheckBox.isSelected()) {
                            checkBoxSt = true;
                            userSt = user;
                            passSt = password;
                        } else {
                            checkBoxSt = false;
                            userSt = null;
                            passSt = null;
                            clearFields();
                        }
                        this.setVisible(false);
                        studentFrame = new StudentFrame(student, courses);
                        studentFrame.setVisible(true);
                    }
                }
            } else {
                for (var x : faculties) {
                    if (x.getEmail().equalsIgnoreCase(user) && x.getPassword().equals(password)) {
                        fac = true;
                        faculty = x;
                        if (rememberCheckBox.isSelected()) {
                            checkBoxFac = true;
                            userFac = user;
                            passFac = password;
                        } else {
                            checkBoxFac = false;
                            userFac = null;
                            passFac = null;
                            clearFields();
                        }
                        this.setVisible(false);
                        facultyFrame = new FacultyFrame(faculty, students);
                        studentFrame.setVisible(true);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill all the fields and try again!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    private void init() {
        demoData();
    }

    private void demoData() {
        students = new ArrayList<>();
        courses = new ArrayList<>();
        departments = new ArrayList<>();
        faculties = new ArrayList<>();

        departments.add(new Department("Computer Science & Engineering", "CSE", "School of Engineering", "PC3F"));
        departments.add(new Department("Electrical & Electronic Engineering", "EEE", "School of Engineering", "PC3F"));
        departments.add(new Department("Bachelor of Business Administration", "BBA", "School of Business", "PD3F"));
        departments.add(new Department("Media Studies & Journalism", "MSJ", "School of Social Science", "PA3F"));
        departments.add(new Department("English and Humanities", "ENG", "School of Arts & Humanities", "PD3F"));
        departments.add(new Department("Bangla Bhasha O Shahitta", "BNG", "chool of Arts & Humanities", "PC2F"));

        faculties.add(new Faculty("John", departments.get(0), "01823", "john@gmail.com"));
        faculties.add(new Faculty("Cena", departments.get(1), "078934", "cena@gmail.com"));
        faculties.add(new Faculty("Alex", departments.get(2), "09786", "alex@gmail.com"));

        students.add(new Student("Nemo", departments.get(0), "Bosila", faculties.get(0)));
        students.add(new Student("Uzo", departments.get(1), "Bosila", faculties.get(1)));
        students.add(new Student("Tee", departments.get(2), "Savar", faculties.get(2)));

        courses.add(new Course("Introduction to Programming", "CSE1102", 1.0, departments.get(0), "Introduces the student to basic of computer programming"));
        courses.add(new Course("Structured Programming", "CSE1201", 3.0, departments.get(2), "Introduces further in structed programming"));
        courses.add(new Course("Object Oriented Programming", "CSE2102", 3.0, departments.get(3), "Object oriented concepts "));
        trimester = new Trimester(223, courses);

        students.get(0).setCurrentTrimester(trimester);
        students.get(1).setCurrentTrimester(trimester);
        students.get(2).setCurrentTrimester(trimester);

        students.get(0).getCurrentTrimester().getCourses().get(0).setMidMarks(20);
        students.get(0).getCurrentTrimester().getCourses().get(0).setFinalMarks(25);
        students.get(0).getCurrentTrimester().getCourses().get(0).setOtherMarks(20);

        students.get(1).getCurrentTrimester().getCourses().get(1).setMidMarks(25);
        students.get(1).getCurrentTrimester().getCourses().get(1).setFinalMarks(30);
        students.get(1).getCurrentTrimester().getCourses().get(1).setOtherMarks(15);
    }

    public static ArrayList<Faculty> faculties;
    public static ArrayList<Student> students;
    public ArrayList<Course> courses;
    public static ArrayList<Department> departments;
    public Trimester trimester;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton buttonForgetPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JCheckBox rememberCheckBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
